# Generated by Django 6.0.3 on 2026-08-06 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudetestattempt',
            name='proctoring_score',
            field=models.IntegerField(default=100, help_text='Proctoring integrity score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='aptitudetestattempt',
            name='proctoring_violations',
            field=models.JSONField(blank=True, default=list, help_text='List of proctoring violations'),
        ),
        migrations.AddField(
            model_name='aptitudetestattempt',
            name='tab_switches',
            field=models.IntegerField(default=0, help_text='Number of tab switches detected'),
        ),
    ]
