# Generated by Django 6.0.3 on 2026-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aptitudetestattempt_proctoring_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudetestattempt',
            name='disqualification_reason',
            field=models.CharField(blank=True, help_text='Why the attempt was disqualified', max_length=255),
        ),
        migrations.AddField(
            model_name='aptitudetestattempt',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='Attempt voided due to proctoring violations'),
        ),
    ]
